export {default as Home} from './Home/Home'
export {default as CompanyProfile} from './CompanyProfile/CompanyProfile'
export {default as ProductandServices} from './ProductandServices/ProductandServices'
export {default as Projects} from './Projects/Projects'
export {default as TechnicalCapabilities} from './TechnicalCapabilities/TechnicalCapabilities'
export {default as EquipmentandFacilities} from './EquipmentandFacilities/EquipmentandFacilities'
export {default as Contactus} from './Contactus/Contactus'