export {default as Home} from './Home/Home'
export {default as CompanyProfile} from './CompanyProfile/CompanyProfile'
export {default as ProductsandServices} from './ProductsandServices/ProductsandServices'
export {default as Projects} from './Projects/Projects'
export {default as TechnicalCapabilities} from './TechnicalCapabilities/TechnicalCapabilities'
export {default as EquipmentsandFacilities} from './EquipmentsandFacilities/EquipmentsandFacilities'
export {default as Contactus} from './Contactus/Contactus'